# Copyright (C) 2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: foldingnetplus
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - torch
  # Dev
  - pre-commit
  - black>=22
  - flake8
